server:
  port: 8001 #服务端口号
spring:
  application:
    name: microServiceCloudProviderDept #微服务名称，对外暴漏的微服务名称，十分重要
  datasource:
    username: root
    password: "123456"
    url: jdbc:mysql://localhost:3306/spring_cloud_db1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  #mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.example.entity
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #这个地址是 7001注册中心在 application.yml 中暴露出来的注册地址 （单机版）
  instance:
    instance-id: spring-cloud-provider-8001 #自定义服务名称信息
    prefer-ip-address: true #显示访问路径的 ip 地址
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*" # * 在yaml 文件属于关键字，所以需要加引号
info:
  app.name: ${spring.application.name} #micro-service-cloud-provider-Dept
  company.name: example.org
  build.artifactId: @project.artifactId@
  build.version: @project.version@