server:
  port: 8003
spring:
  application:
    name: MicroServiceCloudProviderUser
  datasource:
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_db1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka
  instance:
    instance-id: user-info-provider-8003
    prefer-ip-address: true
